version: '3.7'

services:
    app:
        build: .
        container_name: codenation_challenges_app
        command: jupyter notebook --port=8888 --ip=0.0.0.0 --allow-root
        volumes:
            - .:/app
        ports:
            - 8888:8888